apiVersion: batch/v1
kind: CronJob
metadata:
  name: reminder
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: reminder
              image: reminder-image
              resources:
                requests:
                  cpu: "50m"
                  memory: "64Mi"
                limits:
                  cpu: "100m"
                  memory: "128Mi"
              env:
                - name: WIKI_URL
                  valueFrom:
                    configMapKeyRef:
                      name: todo-backend-configmap
                      key: WIKI_URL
          restartPolicy: OnFailure
